services:
  portainer:
    build: common/portainer/.
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      transcendence:

  adminer:
    build: common/adminer/.
    container_name: adminer
    ports:
      - "9000"
    networks:
      transcendence:

  nginx:
    build: common/nginx/.
    container_name: nginx
    depends_on:
      - adminer
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      transcendence:

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
      transcendence:

  # ELK:
  #   build: common/ELK/.
  #   container_name: ELK
  #   ports:
  #     - "5601:5601"
  #     - "9200:9200"
  #     - "5044:5044"
  #   networks:
  #     transcendence:

volumes:
  portainer_data:
  postgres_data:

networks:
  transcendence:
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.1.1.0/28
