# Generated by Django 5.1.2 on 2024-10-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergame',
            name='elo_after',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
