# Generated by Django 5.1.1 on 2024-10-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_elo_after_player1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='games',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='ai_players',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='UUID_LOBBY',
        ),
        migrations.DeleteModel(
            name='Game_Tournament',
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
