# Generated by Django 5.1.1 on 2024-10-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_tournament_games_remove_lobby_ai_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='winner_id',
            field=models.IntegerField(null=True),
        ),
    ]
