# Generated by Django 5.1.1 on 2024-10-05 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_winner_game_winner_id'),
        ('users', '0002_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_games', to='users.player'),
        ),
        migrations.CreateModel(
            name='Game_Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.IntegerField(default=0)),
                ('ai_players', models.ManyToManyField(related_name='games', to='game.aiplayer')),
                ('custom_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.pongcustomgame')),
                ('next_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_game', to='game.game_tournament')),
                ('players', models.ManyToManyField(related_name='games', to='users.player')),
                ('winner_ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='game.aiplayer')),
                ('winner_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Lobby', max_length=255)),
                ('ai_players', models.ManyToManyField(blank=True, related_name='lobbies', to='game.aiplayer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='users.player')),
                ('players', models.ManyToManyField(related_name='lobbies', to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('UUID_LOBBY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby', to='game.lobby')),
                ('games', models.ManyToManyField(related_name='tournament', to='game.game_tournament')),
            ],
        ),
        migrations.AddField(
            model_name='game_tournament',
            name='UUID_TOURNAMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='game.tournament'),
        ),
    ]
