# Generated by Django 5.1.2 on 2024-10-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_winner_id_game_winner_game_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='games',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='ai_players',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='UUID_LOBBY',
        ),
        migrations.DeleteModel(
            name='Game_Tournament',
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
