# Generated by Django 5.1.2 on 2024-10-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
                ('img', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eloPong', models.PositiveIntegerField(default=1000)),
                ('eloConnect4', models.PositiveIntegerField(default=1000)),
                ('is_online', models.BooleanField(default=False)),
                ('lastConnexion', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
