# Generated by Django 5.1.2 on 2024-10-09 02:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='gameUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
