# Generated by Django 5.1.1 on 2024-10-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
